"""Leviton API"""
API_ENDPOINT = "https://my.leviton.com/api"

BULB_THRESHOLD_NORMAL = "normal"
BULB_THRESHOLD_MEDIUM = "medium"
BULB_THRESHOLD_EXTENDED = "extended"
BULB_THRESHOLD_UNKNOWN = "unknown"

BULB_THRESHOLD_MAP = {
    80: BULB_THRESHOLD_NORMAL,
    92: BULB_THRESHOLD_MEDIUM,
    97: BULB_THRESHOLD_EXTENDED,
}

SECOND_GENERATION_MODELS = (
    "D215P",
    "D215R",
    "D215S",
    "D23LP",
    "D24SF",
    "D26HD",
    "D2MSD",
    "D2SCS",
)

SUPPORTED_MODELS_CONTROLLER = (
    "D2SCS",
    "DW4BC",
)
SUPPORTED_MODELS_FAN = (
    "D24SF",
    "DW4SF",
)
SUPPORTED_MODELS_LIGHT = (
    "D23LP",
    "D26HD",
    "D2MSD",
    "DW1KD",
    "DW3HL",
    "DW6HD",
    "DWVAA",
)
SUPPORTED_MODELS_MOTION_SENSOR = (
    "D2MSD",
)
SUPPORTED_MODELS_OUTLET = (
    "D215P",
    "D215R",
    "DW15A",
    "DW15P",
    "DW15R",
)
SUPPORTED_MODELS_SWITCH = (
    "D215S",
    "D2SCS",
    "DW15S",
)

MODEL_GENERATION_1 = 1
MODEL_GENERATION_2 = 2

MODEL_TYPE_CONTROLLER = "controller"
MODEL_TYPE_FAN = "fan"
MODEL_TYPE_LIGHT = "light"
MODEL_TYPE_OUTLET = "outlet"
MODEL_TYPE_SWITCH = "switch"

SUPPORTED_MODELS_MAP = {
    "D215P": [MODEL_TYPE_OUTLET, MODEL_GENERATION_2],
    "D215R": [MODEL_TYPE_OUTLET, MODEL_GENERATION_2],
    "D215S": [MODEL_TYPE_SWITCH, MODEL_GENERATION_2],
    "D23LP": [MODEL_TYPE_LIGHT, MODEL_GENERATION_2],
    "D24SF": [MODEL_TYPE_FAN, MODEL_GENERATION_2],
    "D26HD": [MODEL_TYPE_LIGHT, MODEL_GENERATION_2],
    "D2MSD": [MODEL_TYPE_LIGHT, MODEL_GENERATION_2],
    "D2SCS": [MODEL_TYPE_CONTROLLER, MODEL_GENERATION_2],
    "DW15A": [MODEL_TYPE_OUTLET, MODEL_GENERATION_1],
    "DW15P": [MODEL_TYPE_OUTLET, MODEL_GENERATION_1],
    "DW15R": [MODEL_TYPE_OUTLET, MODEL_GENERATION_1],
    "DW15S": [MODEL_TYPE_SWITCH, MODEL_GENERATION_1],
    "DW1KD": [MODEL_TYPE_LIGHT, MODEL_GENERATION_1],
    "DW3HL": [MODEL_TYPE_LIGHT, MODEL_GENERATION_1],
    "DW4BC": [MODEL_TYPE_CONTROLLER, MODEL_GENERATION_1],
    "DW4SF": [MODEL_TYPE_FAN, MODEL_GENERATION_1],
    "DW6HD": [MODEL_TYPE_LIGHT, MODEL_GENERATION_1],
    "DWVAA": [MODEL_TYPE_LIGHT, MODEL_GENERATION_1],
}

STATUS_LED_MODE_OFF = "led_always_off"
STATUS_LED_MODE_STATUS = "status_mode"
STATUS_LED_MODE_LOCATOR = "locator_mode"
STATUS_LED_MODE_UNKNOWN = "unknown"

STATUS_LED_MODE_MAP = {
    0: STATUS_LED_MODE_OFF,
    254: STATUS_LED_MODE_STATUS,
    255: STATUS_LED_MODE_LOCATOR,
}

STATUS_LED_ENABLED = 255
STATUS_LED_DISABLED = 0

DIM_LED_MODE_OFF = "always_off"
DIM_LED_MODE_ON = "always_on"

TIME_PERIOD_0_SECONDS = "0_seconds"
TIME_PERIOD_0_5_SECONDS = "0_5_seconds"
TIME_PERIOD_1_SECOND = "1_second"
TIME_PERIOD_1_5_SECONDS = "1_5_seconds"
TIME_PERIOD_2_SECONDS = "2_seconds"
TIME_PERIOD_3_SECONDS = "3_seconds"
TIME_PERIOD_5_SECONDS = "5_seconds"
TIME_PERIOD_10_SECONDS = "10_seconds"
TIME_PERIOD_15_SECONDS = "15_seconds"
TIME_PERIOD_25_SECONDS = "25_seconds"

TIME_PERIOD_1_MINUTE = "1_minute"
TIME_PERIOD_2_MINUTES = "2_minutes"
TIME_PERIOD_3_MINUTES = "3_minutes"
TIME_PERIOD_4_MINUTES = "4_minutes"
TIME_PERIOD_5_MINUTES = "5_minutes"
TIME_PERIOD_6_MINUTES = "6_minutes"
TIME_PERIOD_7_MINUTES = "7_minutes"
TIME_PERIOD_8_MINUTES = "8_minutes"
TIME_PERIOD_9_MINUTES = "9_minutes"
TIME_PERIOD_10_MINUTES = "10_minutes"
TIME_PERIOD_15_MINUTES = "15_minutes"
TIME_PERIOD_20_MINUTES = "20_minutes"
TIME_PERIOD_25_MINUTES = "25_minutes"
TIME_PERIOD_30_MINUTES = "30_minutes"
TIME_PERIOD_45_MINUTES = "45_minutes"
TIME_PERIOD_60_MINUTES = "60_minutes"

TIME_PERIOD_1_HOUR = "1_hour"
TIME_PERIOD_2_HOURS = "2_hours"
TIME_PERIOD_3_HOURS = "3_hours"
TIME_PERIOD_4_HOURS = "4_hours"
TIME_PERIOD_5_HOURS = "5_hours"
TIME_PERIOD_6_HOURS = "6_hours"
TIME_PERIOD_7_HOURS = "7_hours"
TIME_PERIOD_8_HOURS = "8_hours"
TIME_PERIOD_9_HOURS = "9_hours"
TIME_PERIOD_10_HOURS = "10_hours"
TIME_PERIOD_11_HOURS = "11_hours"
TIME_PERIOD_12_HOURS = "12_hours"

TIME_PERIOD_UNKNOWN = "unknown"

DIM_LED_MAP = {
    0: DIM_LED_MODE_OFF,
    1: TIME_PERIOD_1_SECOND,
    2: TIME_PERIOD_2_SECONDS,
    3: TIME_PERIOD_3_SECONDS,
    5: TIME_PERIOD_5_SECONDS,
    10: TIME_PERIOD_10_SECONDS,
    15: TIME_PERIOD_15_SECONDS,
    25: TIME_PERIOD_25_SECONDS,
    255: DIM_LED_MODE_ON,
}

LOAD_TYPE_INCANDESCENT = "incandescent"
LOAD_TYPE_LED = "led"
LOAD_TYPE_CFL = "cfl"
LOAD_TYPE_NON_DIMMABLE = "non_dimmable"
LOAD_TYPE_MLV = "mlv"
LOAD_TYPE_UNKNOWN = "unknown"

LOAD_TYPE_MAP = {
    0: LOAD_TYPE_INCANDESCENT,
    1: LOAD_TYPE_LED,
    2: LOAD_TYPE_CFL,
    5: LOAD_TYPE_NON_DIMMABLE,
    4: LOAD_TYPE_MLV,
}

FADE_ON_OFF_RATE_MAP = {
    0: TIME_PERIOD_0_SECONDS,
    5: TIME_PERIOD_0_5_SECONDS,
    10: TIME_PERIOD_1_SECOND,
    15: TIME_PERIOD_1_5_SECONDS,
    20: TIME_PERIOD_2_SECONDS,
    30: TIME_PERIOD_3_SECONDS,
    50: TIME_PERIOD_5_SECONDS,
    100: TIME_PERIOD_10_SECONDS,
    150: TIME_PERIOD_15_SECONDS,
    250: TIME_PERIOD_25_SECONDS,
}

MINIMUM_LEVEL_FAN = 25
MINIMUM_LEVEL_LIGHT = 1
MAXIMUM_LEVEL = 100

STEP_LEVEL_FAN = 25
STEP_LEVEL_LIGHT = 1

PRESET_LEVEL_OFF = 0

AUTO_SHUTOFF_DISABLED = "disabled"

AUTO_SHUTOFF_MAP = {
    0: AUTO_SHUTOFF_DISABLED,
    60: TIME_PERIOD_1_MINUTE,
    300: TIME_PERIOD_5_MINUTES,
    600: TIME_PERIOD_10_MINUTES,
    900: TIME_PERIOD_15_MINUTES,
    1800: TIME_PERIOD_30_MINUTES,
    3600: TIME_PERIOD_1_HOUR,
    7200: TIME_PERIOD_2_HOURS,
    10800: TIME_PERIOD_3_HOURS,
    14400: TIME_PERIOD_4_HOURS,
    18000: TIME_PERIOD_5_HOURS,
    21600: TIME_PERIOD_6_HOURS,
    25200: TIME_PERIOD_7_HOURS,
    28800: TIME_PERIOD_8_HOURS,
    32400: TIME_PERIOD_9_HOURS,
    36000: TIME_PERIOD_10_HOURS,
    39600: TIME_PERIOD_11_HOURS,
    43200: TIME_PERIOD_12_HOURS,
}

MOTION_NIGHT_MODE_ROOM = "room_lights"
MOTION_NIGHT_MODE_GUIDE = "guidelight"
MOTION_NIGHT_MODE_UNKNOWN = "unknown"

MOTION_NIGHT_MODE_MAP = {
    0: MOTION_NIGHT_MODE_ROOM,
    2: MOTION_NIGHT_MODE_GUIDE,
}

MOTION_MODE_OCCUPANCY = "occupancy"
MOTION_MODE_VACANCY = "vacancy"
MOTION_MODE_UNKNOWN = "unknown"

MOTION_MODE_MAP = {
    0: MOTION_MODE_OCCUPANCY,
    1: MOTION_MODE_VACANCY,
}

MOTION_TIMEOUT_MAP = {
    1: TIME_PERIOD_1_MINUTE,
    2: TIME_PERIOD_2_MINUTES,
    3: TIME_PERIOD_3_MINUTES,
    4: TIME_PERIOD_4_MINUTES,
    5: TIME_PERIOD_5_MINUTES,
    6: TIME_PERIOD_6_MINUTES,
    7: TIME_PERIOD_7_MINUTES,
    8: TIME_PERIOD_8_MINUTES,
    9: TIME_PERIOD_9_MINUTES,
    10: TIME_PERIOD_10_MINUTES,
    15: TIME_PERIOD_15_MINUTES,
    20: TIME_PERIOD_20_MINUTES,
    25: TIME_PERIOD_25_MINUTES,
    30: TIME_PERIOD_30_MINUTES,
    45: TIME_PERIOD_45_MINUTES,
    60: TIME_PERIOD_60_MINUTES,
}
MOTION_TIMEOUT_UNKNOWN = "unknown"